//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mytable
    {
        public int id { get; set; }
        public Nullable<int> my_number { get; set; }
        public string my_string { get; set; }
        public string my_string2 { get; set; }
    }
}
